[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codemagic-mcp"
version = "0.1.0"
description = "Simple MCP server for Codemagic CI/CD"
authors = [{ name = "Stefano Amorelli", email = "stefano@amorelli.tech" }]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ["mcp[cli]>=1.6.0", "requests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["codemagic_mcp"]

[project.urls]
"Homepage" = "https://github.com/stefanoamorelli/codemagic-mcp"
"Bug Tracker" = "https://github.com/stefanoamorelli/codemagic-mcp/issues"
